sudo: required
language: c
before_install:
- df -h
- sudo dpkg --add-architecture i386
- sudo apt-get update >/dev/null
install:
- sudo pip install pylzma
- sudo -E apt-get -y install mingw-w64 g++-mingw-w64-x86-64 g++-mingw-w64-i686 debootstrap
  cython make wine xvfb python-pip >/dev/null
- pip install --user git+https://github.com/kivy/buildozer
services:
- docker
os:
- linux
dist: trusty
before_script:
- pip install flake8
- flake8 $TRAVIS_BUILD_DIR/pupy
- cd $TRAVIS_BUILD_DIR/pupy && rm -f payload_templates/pupy*
- if [ -f $HOME/.cache/win.tgz ]; then tar -C $TRAVIS_BUILD_DIR/client/sources -zxf
  $HOME/.cache/win.tgz; fi
- if [ -f $HOME/.cache/lin.tgz ]; then sudo -E tar -C $TRAVIS_BUILD_DIR/client/sources-linux
  -zxf $HOME/.cache/lin.tgz; fi
- if [ -f $HOME/.cache/android.tgz ]; then tar -C $HOME -zxf $HOME/.cache/android.tgz;
  fi
- if [ -f $HOME/.cache/android-app.tgz ]; then tar -C $TRAVIS_BUILD_DIR/client/android_sources
  -zxf $HOME/.cache/android-app.tgz; fi
script:
- sh -e /etc/init.d/xvfb start || systemctl start xvfb
- sleep 3
- df -h
- "( cd $TRAVIS_BUILD_DIR/client/sources && ./buildenv.sh ) & ( cd $TRAVIS_BUILD_DIR/client/android_sources && ./build.sh && rm -f $HOME/.buildozer/android-sdk_* && rm -rf $HOME/.buildozer/android-ndk*) & ( cd $TRAVIS_BUILD_DIR/client/sources-linux && sudo -E ./buildenv.sh ) & wait"
- df -h
- "( cd $TRAVIS_BUILD_DIR/client/sources && ./build.sh )"
- "( cd $TRAVIS_BUILD_DIR/client/sources-linux && sudo -E ./build.sh )"
- ls -l $TRAVIS_BUILD_DIR/pupy/payload_templates
- ls -l $TRAVIS_BUILD_DIR/pupy/payload_templates/pupyx64*.lin
- ls -l $TRAVIS_BUILD_DIR/pupy/payload_templates/pupyx64*.so
- ls -l $TRAVIS_BUILD_DIR/pupy/payload_templates/pupyx64*.dll
- ls -l $TRAVIS_BUILD_DIR/pupy/payload_templates/pupyx64*.exe
- ls -l $TRAVIS_BUILD_DIR/pupy/payload_templates/pupyx86*.lin
- ls -l $TRAVIS_BUILD_DIR/pupy/payload_templates/pupyx86*.so
- ls -l $TRAVIS_BUILD_DIR/pupy/payload_templates/pupyx86*.dll
- ls -l $TRAVIS_BUILD_DIR/pupy/payload_templates/pupyx86*.exe
- ls -l $TRAVIS_BUILD_DIR/pupy/payload_templates/pupy.apk
- ls -l $TRAVIS_BUILD_DIR/pupy/payload_templates/windows-amd64.zip
- ls -l $TRAVIS_BUILD_DIR/pupy/payload_templates/windows-x86.zip
- ls -l $TRAVIS_BUILD_DIR/pupy/payload_templates/linux-amd64.zip
- ls -l $TRAVIS_BUILD_DIR/pupy/payload_templates/linux-x86.zip
- df -h

before_cache:
- rm -rf $HOME/.cache && mkdir -p $HOME/.cache
- rm -rf $TRAVIS_BUILD_DIR/client/sources/buildenv/downloads
- sudo rm -rf $TRAVIS_BUILD_DIR/client/sources-linux/buildenv/downloads
- rm -rf $TRAVIS_BUILD_DIR/client/android_sources/.buildozer/android/app
- "( if [ ! -f $HOME/.cache/win.tgz ]; then tar --remove-files -C $TRAVIS_BUILD_DIR/client/sources
  -zcf $HOME/.cache/win.tgz buildenv; fi; rm -rf $TRAVIS_BUILD_DIR/client/sources/buildenv
  ) & ( if [ ! -f $HOME/.cache/lin.tgz ]; then sudo -E tar --remove-files -C $TRAVIS_BUILD_DIR/client/sources-linux
  -zcf $HOME/.cache/lin.tgz buildenv; fi; sudo rm -rf $TRAVIS_BUILD_DIR/client/sources-linux/buildenv
  ) & ( if [ ! -f $HOME/.cache/android-app.tgz ]; then tar --remove-files -C $TRAVIS_BUILD_DIR/client/android_sources
  -zcf $HOME/.cache/android-app.tgz .buildozer; fi; rm -rf $TRAVIS_BUILD_DIR/client/android_sources/.buildozer
  ) & ( if [ ! -f $HOME/.cache/android.tgz ]; then tar --remove-files -C $HOME -zcf
  $HOME/.cache/android.tgz .android .buildozer/android/platform/android-sdk-20 .buildozer/android/platform/apache-ant-1.9.4;
  fi; rm -rf $HOME/.buildozer ) & wait"
- df -h
cache:
  apt: true
  directories:
  - "$HOME/.cache"
after_cache:
- rm -f $HOME/.cache/win.tgz $HOME/.cache/lin.tgz $HOME/.cache/android.tgz
env:
  global:
  - WINEDEBUG="-all"
  - DISPLAY=":99.0"
  - COMMIT=${TRAVIS_COMMIT::8}
before_deploy:
- rm -f $TRAVIS_BUILD_DIR/pupy/payload_templates/*.lib
- rm -f $TRAVIS_BUILD_DIR/pupy/payload_templates/*.exp
- rm -f $TRAVIS_BUILD_DIR/pupy/payload_templates/pupy*d.dll
- rm -f $TRAVIS_BUILD_DIR/pupy/payload_templates/pupy*d.lin.so
- rm -f $TRAVIS_BUILD_DIR/pupy/payload_templates/pupy*d.unc.*
- tar -C $TRAVIS_BUILD_DIR --exclude=Dockerfile --exclude=.dockerignore --exclude=.git --exclude=winpty --exclude=scapy -Jcf $TRAVIS_BUILD_DIR/pupy.txz pupy
- tar -C $TRAVIS_BUILD_DIR/pupy -Jcf $TRAVIS_BUILD_DIR/payload_templates.txz payload_templates
deploy:
  provider: releases
  api_key:
    secure: E3nJgSrYLIIil6eqP0h0c67Ktaw9QN7IfNDsaIuQwstZE/kBIJe9DIY93oaN+1soosknXHm/dsLeraNZVYXJbsoE9lPuDzOdC2sBq09xAR+ZRFXdtUMXtMDv816v2ZsdHZbfbNvm5ucixE9eGXDGPpDYcJRliHpAFPavysHL3lvF0dem1rI2RQsB0LGRYGOVFwjpdpqFITZs1BZxq/clXbqBLBnJO30D3LUdbXWYCqC4M4fMIIQOsWZRLGu8JgD6stmB8t+ve7XcXy4JhE6jFNgzMP6DHYoloobeUWWk6RbsAPs4j3UYbYFCsuow+JJ9iaXP0sgv8gST3nqjZtF1xiRVYOdqTa2MIAkGIuOmH1otl55C6UuXdIZGd6SPOKlKC3ccB92KcDy+7h5QcH16mFqZKsOkYRAE4izaE9GyWejpFxlnqOZGLwN8AKsf/zpWq4bRbEAYLWayi1KYNzGlFwsbdf7BWZJ90JWmVpf1AcJ92sbNexxkoW47Jm+Ir264ZK72IWLdE9PYkNUi5wt6IhsHsshdVlUa0p3qvIgBeWdfm+fgcm7qyJbCp37SFgbYmcs4+9U9B75lPpYR7RZOdGh3NGcREFbzYVz+VpPOaDGEJ4mBWn3DXcLtnjBG4q28/eDSkvrq1QK1g8+urzml6KYHaH738tRbjV97YsHsAvM=
  file:
    - "$TRAVIS_BUILD_DIR/pupy.txz"
    - "$TRAVIS_BUILD_DIR/payload_templates.txz"
  skip_cleanup: true
  on:
    repo: n1nj4sec/pupy
    tags: true
